version: "3.8"

services:
  uhf-server:
    image: ghcr.io/RyDizz214/uhf-server-docker:1.4.0
    container_name: uhf-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:8000"
    volumes:
      - "${HOST_RECORDINGS_DIR}:/recordings"
      - "${HOST_UHF_DATA_DIR}:/var/lib/uhf-server"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/server/stats"]
      interval: 60s
      timeout: 10s
      retries: 3
